In [2]:
import pandas as pd
import re

# 1) Load CSV data (adjust filename & column names to your dataset).
df = pd.read_csv("quran_data.csv")
print(df.head())  # quick look at the first few rows

   surah_no surah_name_en surah_name_ar surah_name_roman  ayah_no_surah  \
0         1    The Opener       الفاتحة       Al-Fatihah              1
1         1    The Opener       الفاتحة       Al-Fatihah              2
2         1    The Opener       الفاتحة       Al-Fatihah              3
3         1    The Opener       الفاتحة       Al-Fatihah              4
4         1    The Opener       الفاتحة       Al-Fatihah              5

   ayah_no_quran                                   ayah_ar  \
0              1    بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ
1              2     ٱلْحَمْدُ لِلَّهِ رَبِّ ٱلْعَٰلَمِينَ
2              3                   ٱلرَّحْمَٰنِ ٱلرَّحِيمِ
3              4                   مَٰلِكِ يَوْمِ ٱلدِّينِ
4              5  إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ

                                             ayah_en  ruko_no  juz_no  \
0  In the Name of Allah—the Most Compassionate, M...        1       1
1        All praise is for Allah—Lord of all worlds,        1       1
2             the Most Compassionate, Most Merciful,        1       1
3                     Master of the Day of Judgment.        1       1
4  You ˹alone˺ we worship and You ˹alone˺ we ask ...        1       1

   manzil_no  hizb_quarter  total_ayah_surah  total_ayah_quran  \
0          1             1                 7              6236
1          1             1                 7              6236
2          1             1                 7              6236
3          1             1                 7              6236
4          1             1                 7              6236

  place_of_revelation  sajah_ayah  sajdah_no  no_of_word_ayah  \
0              Meccan       False        NaN                4
1              Meccan       False        NaN                4
2              Meccan       False        NaN                2
3              Meccan       False        NaN                3
4              Meccan       False        NaN                4

                                list_of_words
0    [بِسْمِ,ٱللَّهِ,ٱلرَّحْمَٰنِ,ٱلرَّحِيمِ]
1     [ٱلْحَمْدُ,لِلَّهِ,رَبِّ,ٱلْعَٰلَمِينَ]
2                   [ٱلرَّحْمَٰنِ,ٱلرَّحِيمِ]
3                   [مَٰلِكِ,يَوْمِ,ٱلدِّينِ]
4  [إِيَّاكَ,نَعْبُدُ,وَإِيَّاكَ,نَسْتَعِينُ]

In [12]:
import re

# Function to remove diacritics and normalize text
def normalize_arabic(text):
    # Remove diacritics (harakaat)
    diacritic_pattern = re.compile(r'[\u0617-\u061A\u064B-\u0652\u0657-\u065B\u06D6-\u06ED]')
    text = re.sub(diacritic_pattern, '', text)
    
    # Normalize Alifs (أ, إ, آ, ٱ → ا)
    text = re.sub(r'[أإآٱ]', 'ا', text)
    
    # Optionally normalize Taa Marbuta (ة → ه) if relevant
    # text = text.replace('ة', 'ه')
    
    return text

# Apply normalization to the "ayah_ar" column
df["ayah_normalized"] = df["ayah_ar"].apply(normalize_arabic)

# Example: Search for a concept
def search_concept(word, df, column="ayah_normalized"):
    # Normalize the search word
    word_normalized = normalize_arabic(word)
    
    # Check which verses contain the word
    mask = df[column].str.contains(word_normalized, na=False)
    matches = df[mask]
    return matches

# Example Usage: Find verses with the concept "الدنيا"
concept = "الدنيا"
results = search_concept(concept, df)
print(f"Found {len(results)} verses containing the concept '{concept}'.")
results[["surah_no", "ayah_no_surah", "ayah_ar"]].head()

Found 111 verses containing the concept 'الدنيا'.

,surah_no,ayah_no_surah,ayah_ar
91,2,85,ثُمَّ أَنتُمْ هَٰٓؤُلَآءِ تَقْتُلُونَ أَنفُسَ...
92,2,86,أُو۟لَٰٓئِكَ ٱلَّذِينَ ٱشْتَرَوُا۟ ٱلْحَيَوٰةَ...
120,2,114,وَمَنْ أَظْلَمُ مِمَّن مَّنَعَ مَسَٰجِدَ ٱللَّ...
136,2,130,وَمَن يَرْغَبُ عَن مِّلَّةِ إِبْرَٰهِۦمَ إِلَّ...
206,2,200,فَإِذَا قَضَيْتُم مَّنَٰسِكَكُمْ فَٱذْكُرُوا۟ ...

In [17]:

# Updated list of concepts
concepts = {
    "دنيا": "This World",
    "آخرة": "The Hereafter",
    "ملائكة": "Angels",
    "شياطين": "Satan",
    "حياة": "Life",
    "موت": "Death",
    "رجل": "Man",
    "امرأة": "Woman",
    "شهر": "Month",
    "يوم": "Day",
    "بحر": "Sea",
    "بر": "Land"
}

          Concept  Occurrences
9             Day          211
6             Man           13
7           Woman            3
8           Month            3
11           Land            3
10            Sea            1
0      This World            0
1   The Hereafter            0
2          Angels            0
3           Satan            0
4            Life            0
5           Death            0